version: '3.9'
services: 
    blog-api:
        image: blog-api
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - "8080:80"
    
    db:
        image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
        environment: 
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"

